
---
<<<<<<< HEAD
title: Title
author: Authors
output: word_document
---

=======
title: 'STAT2003: Assignment 1'
author: "Samantha Clements and Kafula Chewe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

>>>>>>> cd2e42b047ba298b0c430a72971b1b9ceeeeaf72
```{r}
# install.packages("ISLR", dependencies = TRUE)
# install.packages("caret", dependencies = TRUE)
# install.packages("e1071", dependencies = TRUE)
# install.packages("randomForest", dependencies = TRUE)
# install.packages("DiagrammeR", dependencies = TRUE)
```


```{r}

library(ISLR)
library(caret)
library(e1071)
library(randomForest)
library(DiagrammeR)

```

```{r DOE Diagram}
# sources:
# https://www.sesync.org/resources/creating-visualizations-diagrammer 
# clusters: https://graphviz.org/pdf/dotguide.pdf

DOE_Diagram <- grViz("digraph{
         
                     graph[layout = dot, rankdir = LR, splines = line] # Left to Right
                     
                     node[shape = rectangle, style = filled]
                     
                    # Central box
                    
                    centre_box [label = '\n\n\nDOE\n\n\n\n', 
                    shape = box, fillcolor = lightblue, width = 3]\
                    
                    # Inputs
                    
                    subgraph cluster_input {
                    
                    
                    X1 [label = 'X1: Model Type: \nLogistic Regression,\nRandom Forest,\nNaive Bayes,\nSupport Vector Machine']
                    
                    {rank = same
                    edge [constraint = false, style = invis]
                    
                    # Vertically stacked
                    X1 }
                    
                    }
                    
                    
                    # Noise
                    subgraph cluster_noise {
                    
                    N1 [label = 'N1: Random Sampling Variation']
                    N2 [label = 'N2: Model Randomness']
                    N3 [label = 'N3: CV Fold Assignment Randomness']
                    
                    {edge [style = invis]
                    
                    # Horizontally stacked
                    N1 -> N2 -> N3}
                    
                    }
                    
                    
                    # Constants
                    subgraph cluster_constants {
                    
                    
                    
                    C1 [label = 'C1: Same random seed - set.seed(000)']
                    C2 [label = 'C2: Same Dataset - Default (ISLR)']
                    C3 [label = 'C3: CV - 10 folds, 3 repeats']
                    C4 [label = 'C4: Model Hyperparameters']
                    
                    
                    {edge [style = invis]
                    
                    # Horizontally stacked
                    C1 -> C2 -> C3 -> C4}
                    }
                    
                  
                    # Outputs
                    subgraph cluster_outputs {
                    
                    Y1 [label = 'Y1: AUC-ROC']
                    Y2 [label = 'Y2: Precision']
                    Y3 [label = 'Y3: Recall']
                    
                    {rank = same
                    edge [constraint = false, style = invis]
                    
                    # Vertically stacked
                    Y1 -> Y2 -> Y3}
                    
                    }
                   
                  
                    # Arrows
                    
                    edge [arrowhead = normal, style = solid]
                    X1 -> centre_box [minlen = 2]
                   
                    edge [arrowhead = normal, style = solid]
                    centre_box -> Y1 [minlen = 2.5]
                    centre_box -> Y2
                    centre_box -> Y3
                    
                    edge [constraint = false, arrowhead = normal, style = solid]
                    
                    N1 -> centre_box:s [minlen = 3] 
                    N2 -> centre_box:s [minlen = 3] 
                    N3 -> centre_box:s [minlen = 3]
                    
                    edge [constraint = false, arrowhead = normal, style = solid]
                    C1 -> centre_box:n [minlen = 3]
                    C2 -> centre_box:n [minlen = 3]
                    C3 -> centre_box:n [minlen = 3]
                    C4 -> centre_box:n [minlen = 3]
                    
                    
                     }")
 
DOE_Diagram
```



```{r}
#Obtaining and inspecting the data
set.seed(000)
data(Default)
Default$default <- factor(Default$default, levels = c("No", "Yes"))
head(Default)

```

```{r}
#Control of the experiment (Conditions that remain the same for all 4 models)
ctrl <- trainControl(method = "repeatedcv",
                     number = 10,
                     repeats = 3,          
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)
```



```{r}
#Training the models
model_lr  <- train(default ~ ., data = Default, method = "glm",
                   family = "binomial", trControl = ctrl, metric = "ROC")

model_rf  <- train(default ~ ., data = Default, method = "rf",  
                   trControl = ctrl, metric = "ROC",
                   tuneLength = 3)  

model_nb  <- train(default ~ ., data = Default, method = "nb",
                   trControl = ctrl, metric = "ROC")

model_svm <- train(default ~ ., data = Default, method = "svmLinear",
                   trControl = ctrl, preProcess = c("center", "scale"),
  tuneLength = 3)
```



```{r}
#Creating a list of all four models
models <- list(LogisticRegression = model_lr,
               RandomForest = model_rf,
               NaiveBayes = model_nb,
               SVM = model_svm)
```

```{r}
#Summary of resampling results
res <- resamples(models)

summary(res)
```

```{r}
#Creates resamples that compares ROC across 30 resamples 
bwplot(res, metric = "ROC",
       main = "ROC AUC across 30 resamples (3×10 repeated CV)")
```

